version: '3.8'
services:
  db:
    image: postgres:14-alpine
    restart: always
    environment:
      POSTGRES_USER: devuser
      POSTGRES_PASSWORD: devpassword
      POSTGRES_DB: luzysaberdb
    volumes:
      - ./pgdata:/var/lib/postgresql/data 
    ports:
      - "5432:5432" 

  server:
    build: . 
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      # Cadena de conexión que usará Prisma, apuntando al servicio 'db'
      DATABASE_URL: postgresql://devuser:devpassword@db:5432/luzysaberdb?schema=public